export const text_practice1 = "Hilf mit, die wilde Natur zu retten! Für jedes"
    + " Stofftier, das du zwischen dem 11.10.2025 und dem 29.11.2025 kaufst, spendet IKEA 1€ an den NABU, um ihre wichtige Arbeit für den Artenschutz zu unterstützen. Gemeinsam können wir etwas bewegen.\n"
    + "\n"
    + "62 ProdukteSortieren und Filtern\n";
export const text_practice2 = "Komm mit und erlebe spannende Abenteuer in der"
    + " Savanne! Mit der Vielfalt an Spielzeugen, Textilien und Accessoires in unserer SANDLÖPARE Kollektion laden wir dich in die bunte Welt des Entdeckens und Lernens ein.\n"
    + "\n";
export const text_trial1 = ""
    + "With the average temperature for January standing at -50°C, it is no wonder the Russian village of Oymyakon is the coldest permanently inhabited settlement in the world. Known as the \"Pole of Cold\", the coldest ever temperature recorded in Oymyakon is -71.2°C. This is the lowest recorded temperature for any permanently inhabited location on Earth and the lowest temperature recorded in the northern hemisphere.\n"
    + "\n"
    + "Ironically, Oymyakon actually means \"nonfreezing water\" due to a nearby hot spring. Most homes in Oymyakon still burn coal and wood for heat and enjoy few modern conveniences.\n"
    + "\n"
    + "Nothing grows there, so people eat reindeer meat and horsemeat. A single shop provides the town's bare necessities and the locals work as reindeer breeders, hunters, and ice fishermen.\n"
    + "\n"
    + "There are few modern conveniences in the village, with many buildings still having outdoor toilets, and most people still burn coal and wood for heat. When coal deliveries are irregular, the power station starts burning wood. If the power ceases, the town shuts down in about five hours, and the pipes freeze and crack.\n"
    + "\n"
    + "Daily problems that come with living in Oymyakon include pen ink freezing, glasses freezing to people's faces, and batteries losing power. Locals are said to leave their cars running all day for fear of not being able to restart them. Even if there was coverage for mobile phone reception, the phones themselves would not work in such conditions.\n"
    + "\n"
    + "Another problem caused by the frozen temperatures is burying dead bodies, which can take anything up to three days. The earth must first have thawed sufficiently in order to dig it, so a bonfire is lit for a couple of hours. Hot coals are then pushed to the side and a hole couple of inches deep is dug. The process is repeated for several days until the hole is deep enough to bury the coffin.\n"
    + "\n"
    + "Travel companies offer tourists the opportunity to visit the village and sample life in freezing conditions.";
export const text_trial2 = ""
    + "Alzheimer's disease is a major national health problem. Nearly 2 million Americans over the age of 65 have Alzheimer's disease. It is a leading cause of death among the elderly. But Alzheimer's disease is not confined to the aged. There may be a million or more people under the age of 65 suffering from the disease.\n"
    + "\n"
    + "At one time, people suffering from the disease were said to be \"getting old\". The disease was thought to be a natural part of growing old, but it is now known that Alzheimer's disease strikes young and old alike. It is an organic disease that destroys brain cells.\n"
    + "\n"
    + "Alzheimer's disease affects the patient's memory, speech, and movement. In the beginning stages of the disease, the patient may seem slightly confused. He may have trouble speaking, then the patient's memory begins to fail. He may forget dates, numbers, names and plans.\n"
    + "\n"
    + "As the disease progresses, the patient may not recognize family and friends. These symptoms often cause terrible anxiety in the patient. He may feel lost and frightened. Sometimes the patient reacts with wild and bad behavior.\n"
    + "\n"
    + "In the last stages of the disease, the patient may not be able to take care of himself. He may have lost the ability to speak and walk.\n"
    + "\n"
    + "Scientists don't know exactly what causes Alzheimer's disease. It may be caused by a virus. It may be caused by a poisonous substance in the environment. At present, there is no cure for the disease. But there are ways to slow its progress. Exercise and physical treatment can help the patients of this disease.";